/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Quoc
 */
public class ElfParserMainForm extends javax.swing.JFrame {

  /**
   * Creates new form ElfParserMainForm
   */
  public ElfParserMainForm() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jPanel2 = new javax.swing.JPanel();
    btnOpen = new javax.swing.JButton();
    btnReset = new javax.swing.JButton();
    btnAbout = new javax.swing.JButton();
    btnClose = new javax.swing.JButton();
    tabContain = new javax.swing.JTabbedPane();
    tabOverview = new javax.swing.JPanel();
    tabELFHeader = new javax.swing.JPanel();
    tabSHeaders = new javax.swing.JPanel();
    tabPHeaders = new javax.swing.JPanel();
    tabSymbols = new javax.swing.JPanel();
    tabCapabilities = new javax.swing.JPanel();
    tabScoring = new javax.swing.JPanel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Score"));

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 0, Short.MAX_VALUE)
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 65, Short.MAX_VALUE)
    );

    jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Controls"));

    btnOpen.setText("Open");
    btnOpen.setName(""); // NOI18N

    btnReset.setText("Reset");

    btnAbout.setText("About");

    btnClose.setText("Close");

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(btnOpen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(btnAbout, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(btnReset, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
          .addComponent(btnClose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap())
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btnOpen)
          .addComponent(btnReset))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btnAbout)
          .addComponent(btnClose))
        .addGap(30, 30, 30))
    );

    javax.swing.GroupLayout tabOverviewLayout = new javax.swing.GroupLayout(tabOverview);
    tabOverview.setLayout(tabOverviewLayout);
    tabOverviewLayout.setHorizontalGroup(
      tabOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 560, Short.MAX_VALUE)
    );
    tabOverviewLayout.setVerticalGroup(
      tabOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 422, Short.MAX_VALUE)
    );

    tabContain.addTab("Overview", tabOverview);

    javax.swing.GroupLayout tabELFHeaderLayout = new javax.swing.GroupLayout(tabELFHeader);
    tabELFHeader.setLayout(tabELFHeaderLayout);
    tabELFHeaderLayout.setHorizontalGroup(
      tabELFHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 560, Short.MAX_VALUE)
    );
    tabELFHeaderLayout.setVerticalGroup(
      tabELFHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 422, Short.MAX_VALUE)
    );

    tabContain.addTab("ELF Header", tabELFHeader);

    javax.swing.GroupLayout tabSHeadersLayout = new javax.swing.GroupLayout(tabSHeaders);
    tabSHeaders.setLayout(tabSHeadersLayout);
    tabSHeadersLayout.setHorizontalGroup(
      tabSHeadersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 560, Short.MAX_VALUE)
    );
    tabSHeadersLayout.setVerticalGroup(
      tabSHeadersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 422, Short.MAX_VALUE)
    );

    tabContain.addTab("SHeaders", tabSHeaders);

    javax.swing.GroupLayout tabPHeadersLayout = new javax.swing.GroupLayout(tabPHeaders);
    tabPHeaders.setLayout(tabPHeadersLayout);
    tabPHeadersLayout.setHorizontalGroup(
      tabPHeadersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 560, Short.MAX_VALUE)
    );
    tabPHeadersLayout.setVerticalGroup(
      tabPHeadersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 422, Short.MAX_VALUE)
    );

    tabContain.addTab("PHeaders", tabPHeaders);

    javax.swing.GroupLayout tabSymbolsLayout = new javax.swing.GroupLayout(tabSymbols);
    tabSymbols.setLayout(tabSymbolsLayout);
    tabSymbolsLayout.setHorizontalGroup(
      tabSymbolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 560, Short.MAX_VALUE)
    );
    tabSymbolsLayout.setVerticalGroup(
      tabSymbolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 422, Short.MAX_VALUE)
    );

    tabContain.addTab("Symbols", tabSymbols);

    javax.swing.GroupLayout tabCapabilitiesLayout = new javax.swing.GroupLayout(tabCapabilities);
    tabCapabilities.setLayout(tabCapabilitiesLayout);
    tabCapabilitiesLayout.setHorizontalGroup(
      tabCapabilitiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 560, Short.MAX_VALUE)
    );
    tabCapabilitiesLayout.setVerticalGroup(
      tabCapabilitiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 422, Short.MAX_VALUE)
    );

    tabContain.addTab("Capabilities", tabCapabilities);

    javax.swing.GroupLayout tabScoringLayout = new javax.swing.GroupLayout(tabScoring);
    tabScoring.setLayout(tabScoringLayout);
    tabScoringLayout.setHorizontalGroup(
      tabScoringLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 560, Short.MAX_VALUE)
    );
    tabScoringLayout.setVerticalGroup(
      tabScoringLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 422, Short.MAX_VALUE)
    );

    tabContain.addTab("Scoring", tabScoring);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(19, 19, 19)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addGap(18, 18, 18)
        .addComponent(tabContain, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(26, 26, 26)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(tabContain, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(layout.createSequentialGroup()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(23, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(ElfParserMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(ElfParserMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(ElfParserMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(ElfParserMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new ElfParserMainForm().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnAbout;
  private javax.swing.JButton btnClose;
  private javax.swing.JButton btnOpen;
  private javax.swing.JButton btnReset;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel tabCapabilities;
  private javax.swing.JTabbedPane tabContain;
  private javax.swing.JPanel tabELFHeader;
  private javax.swing.JPanel tabOverview;
  private javax.swing.JPanel tabPHeaders;
  private javax.swing.JPanel tabSHeaders;
  private javax.swing.JPanel tabScoring;
  private javax.swing.JPanel tabSymbols;
  // End of variables declaration//GEN-END:variables
}
